UKSM: fix compile errors
Conflict with commit "mm: per-thread vma caching":
mm/mmap.c:2434:4: error: 'struct mm_struct' has no member named 'mmap_cache'; did you mean 'mmap_base'?
  mm->mmap_cache = NULL;
    ^~

mm/uksm.c:
[-Werror=deprecated-declarations]

fs/exec.c: In function '__register_binfmt':
fs/exec.c:94:9: error: 'return' with a value, in function returning void [-Werror]
  return 0;

Signed-off-by: UpInTheAir <upintheair.skyhigh@gmail.com>